title: "Samuel Green"
url: "https://sa.muel.green"
baseurl: ""
favicon: favicon.ico

markdown: kramdown

# Configuration
tracking_id: "UA-40106303-1"
twitter_username: "s_m__lgr__n"

sass:
    style: compressed
    sass_dir: _sass
