title: "Samuel Green"
url: "https://greensam.github.io"
baseurl: ""

markdown: kramdown

# Configuration
tracking_id: #
twitter_username: "s_m__lgr__n"

sass:
    style: compressed
    sass_dir: _sass
